CURL = curl -L -o

doc: Cover.pdf ToC.pdf Introduction.pdf Part1.pdf Part2.pdf \
	gpbb1.pdf gpbb2.pdf gpbb3.pdf gpbb4.pdf gpbb5.pdf gpbb6.pdf \
	gpbb7.pdf gpbb8.pdf gpbb9.pdf gpbb10.pdf gpbb11.pdf gpbb12.pdf \
	gpbb13.pdf gpbb14.pdf gpbb15.pdf gpbb16.pdf gpbb17.pdf gpbb18.pdf \
	gpbb19.pdf gpbb20.pdf gpbb21.pdf gpbb22.pdf gpbb23.pdf gpbb24.pdf \
	gpbb25.pdf gpbb26.pdf gpbb27.pdf gpbb28.pdf gpbb29.pdf gpbb30.pdf \
	gpbb31.pdf gpbb32.pdf gpbb33.pdf gpbb34.pdf gpbb35.pdf gpbb36.pdf \
	gpbb37.pdf gpbb38.pdf gpbb39.pdf gpbb40.pdf gpbb41.pdf gpbb42.pdf \
	gpbb43.pdf gpbb44.pdf gpbb45.pdf gpbb46.pdf gpbb47.pdf gpbb48.pdf \
	gpbb49.pdf gpbb50.pdf gpbb51.pdf gpbb52.pdf gpbb53.pdf gpbb54.pdf \
	gpbb55.pdf gpbb56.pdf gpbb57.pdf gpbb58.pdf gpbb59.pdf gpbb60.pdf \
	gpbb61.pdf gpbb62.pdf gpbb63.pdf gpbb64.pdf gpbb65.pdf gpbb66.pdf \
	gpbb67.pdf gpbb68.pdf gpbb69.pdf gpbb70.pdf 

Cover.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb.pdf
ToC.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb0.pdf
Introduction.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbbintr.pdf

Part1.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbbpt1.pdf
Part2.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbbpt2.pdf

Afterword.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbbaftr.pdf
Index.pdf:	
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbbindx.pdf

gpbb1.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb1.pdf
gpbb2.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb2.pdf
gpbb3.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb3.pdf
gpbb4.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb4.pdf
gpbb5.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb5.pdf
gpbb6.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb6.pdf
gpbb7.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb7.pdf
gpbb8.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb8.pdf
gpbb9.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb9.pdf
gpbb10.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb10.pdf
gpbb11.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb11.pdf
gpbb12.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb12.pdf
gpbb13.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb13.pdf
gpbb14.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb14.pdf
gpbb15.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb15.pdf
gpbb16.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb16.pdf
gpbb17.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb17.pdf
gpbb18.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb18.pdf
gpbb19.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb19.pdf
gpbb20.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb20.pdf
gpbb21.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb21.pdf
gpbb22.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb22.pdf
gpbb23.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb23.pdf
gpbb24.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb24.pdf
gpbb25.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb25.pdf
gpbb26.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb26.pdf
gpbb27.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb27.pdf
gpbb28.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb28.pdf
gpbb29.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb29.pdf
gpbb30.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb30.pdf
gpbb31.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb31.pdf
gpbb32.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb32.pdf
gpbb33.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb33.pdf
gpbb34.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb34.pdf
gpbb35.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb35.pdf
gpbb36.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb36.pdf
gpbb37.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb37.pdf
gpbb38.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb38.pdf
gpbb39.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb39.pdf
gpbb40.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb40.pdf
gpbb41.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb41.pdf
gpbb42.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb42.pdf
gpbb43.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb43.pdf
gpbb44.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb44.pdf
gpbb45.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb45.pdf
gpbb46.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb46.pdf
gpbb47.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb47.pdf
gpbb48.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb48.pdf
gpbb49.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb49.pdf
gpbb50.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb50.pdf
gpbb51.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb51.pdf
gpbb52.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb52.pdf
gpbb53.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb53.pdf
gpbb54.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb54.pdf
gpbb55.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb55.pdf
gpbb56.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb56.pdf
gpbb57.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb57.pdf
gpbb58.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb58.pdf
gpbb59.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb59.pdf
gpbb60.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb60.pdf
gpbb61.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb61.pdf
gpbb62.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb62.pdf
gpbb63.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb63.pdf
gpbb64.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb64.pdf
gpbb65.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb65.pdf
gpbb66.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb66.pdf
gpbb67.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb67.pdf
gpbb68.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb68.pdf
gpbb69.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb69.pdf
gpbb70.pdf:
	$(CURL) $@ https://web.archive.org/web/20190706123029/http://twimgs.com/ddj/abrashblackbook/gpbb70.pdf

